### ISSUE TITLE
ios 14 webgl1

### ISSUE THREAD

**Issue by arpu** [MONOGRID/gainmap-js#26]
Hey,

i have done some testing on Browserstack and ios and see a problem on ios 14 devices ( wegl1) 

```Unhandled Promise Rejection: TypeError: images[0].arrayBuffer is not a function. (In 'images[0].arrayBuffer()', 'images[0].arrayBuffer' is undefined)```

![Bildschirmfoto vom 2023-12-04 18-14-39](https://github.com/MONOGRID/gainmap-js/assets/14173/ab7c9977-5dde-45b5-80b3-3faa80152aa6)

**Comment by arpu** [comment]
![Bildschirmfoto vom 2023-12-04 19-15-28](https://github.com/MONOGRID/gainmap-js/assets/14173/ad321660-6886-46cf-a609-432fbefab23c)

but maybe this is nothing worry about, i only want to report, if i get more infos, will update

**Comment by arpu** [comment]
work with webgl1 and iphone 12 Pro v14.2

**Comment by daniele-pelagatti** [comment]
Thanks for reporting back!

**Comment by dghez** [comment]
Just FYI, threejs stopped supporting WEBGL1 too  https://github.com/mrdoob/three.js/wiki/Migration-Guide#162--r163
